{% set version = "0.9-4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-linprog
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/linprog_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/linprog/linprog_{{ version }}.tar.gz
  sha256: 81a6aa2fdc075f12dc912794d0554f87705a8b872b99c89a90a69ee9ada864b4

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-lpsolve
  run:
    - r-base
    - r-lpsolve

test:
  commands:
    - $R -e "library('linprog')"           # [not win]
    - "\"%R%\" -e \"library('linprog')\""  # [win]

about:
  home: http://linprog.r-forge.r-project.org/
  license: GPL-2.0-or-later
  summary: This package can be used to solve Linear Programming / Linear Optimization problems by using the simplex algorithm.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: linprog
# Version: 0.9-2
# Date: 2012/10/17
# Title: Linear Programming / Optimization
# Author: Arne Henningsen
# Maintainer: Arne Henningsen <arne.henningsen@gmail.com>
# Depends: R (>= 2.4.0), lpSolve
# Description: This package can be used to solve Linear Programming / Linear Optimization problems by using the simplex algorithm.
# License: GPL (>= 2)
# URL: http://linprog.r-forge.r-project.org/
# Packaged: 2012-10-17 08:45:29 UTC; arne
# Repository: CRAN
# Date/Publication: 2012-10-17 11:03:12
# NeedsCompilation: no
