appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: OKIcDlCOQhpXTRnz9s4c9H3maVwFNyGk7jQszJgmz00VCUMIHujoFIEVSBRQZRq8fqGehbEUISH0Fd6U3H37rwmJq3ql3nJRpRmWQF4EHt508VelcddBfQmW4uF1e/VIz9AOdxCprTJvNgWAqtPfXRRoObOH1QOk3xrZOggr8X64A6d+/LY+zrn1sEMlNUqL2bjnQgm/xQ21LCQC471vLkvLsraXqx8EhAen1cE9HbuEfdceGJN004t10yHjPlW4ltZa02i9LbsMurIqWghVlDNAIWAKG4VNahXCAFhdfDMRFlWV1/EJlZqiPopiUIZIlQOI0S1f7V3bXuOyYnL2ZpbPttcQaFz4cLoeZBsO9IJCn0TjtLhpr6Ndg0GAYQfmw2h/Bnx0llGzYyEoz7W0kS2/Fe4fE8Cwm4ss7/xuXUuViZMq13v0tagYjR/ggucBv5MOr6fyXeAjBs4DzlyXS96kFBIRgUpfWknUpluzPEVDKpMZzDTbs6oScJnxVZSpibuD/5gtNnx6qpJcawyKfbC5EqI6ca4KriuskTJE+JKtcZAFrv66e+MpythyAlvdWiU+UQm2KUxQdut9aLldV1Xe1rcZc0oaq8frY4e8eh5LsEVg1i2VyJ8AaICYTs+ObEC6BzJ5J6fiPR92r9dLy1jB5RPCdX/jv3kHKw+ul8Q=
